# Generated by Django 2.2.6 on 2019-10-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20191011_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='user',
        ),
    ]
