# Generated by Django 2.2.6 on 2019-10-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20191011_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='max_size',
            field=models.IntegerField(default=10),
        ),
    ]
