# Generated by Django 2.2.6 on 2019-10-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_studygroup_max_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='current_size',
            field=models.IntegerField(default=1),
        ),
    ]
