# Generated by Django 2.2.6 on 2019-10-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_studygroup_current_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='fri',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='mon',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='sat',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='sun',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='thur',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='tue',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='wed',
            field=models.TimeField(default='00:00'),
        ),
    ]
