# Generated by Django 2.2.6 on 2019-10-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_studygroup_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
