# Generated by Django 2.2.6 on 2019-10-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
