# Generated by Django 2.2.6 on 2019-10-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_auto_20191012_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='classes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Classes'),
        ),
    ]
